import {EmailAddress} from './EmailAddress';

export interface Contact {
  assistantName:        string;
  birthday:             string;
  businessAddress:      string;
  businessHomePage:     string;
  businessPhones:       string[];
  categories:           string[];
  changeKey:            string;
  children:             string[];
  companyName:          string;
  createdDateTime:      string;
  department:           string;
  displayName:          string;
  emailAddresses:       EmailAddress[];
  fileAs:               string;
  generation:           string;
  givenName:            string;
  homeAddress:          string;
  homePhones:           string[];
  id:                   string;
  imAddresses:          string[];
  initials:             string;
  jobTitle:             string;
  lastModifiedDateTime: string;
  manager:              string;
  middleName:           string;
  mobilePhone:          string;
  nickName:             string;
  officeLocation:       string;
  otherAddress:         string;
  parentFolderId:       string;
  personalNotes:        string;
  profession:           string;
  spouseName:           string;
  surname:              string;
  title:                string;
  yomiCompanyName:      string;
  yomiGivenName:        string;
  yomiSurname:          string;
  photo:                string;
}
